- .github/auto_request_review.yml
- .github/workflows/package-build.yml
- README.rst
- pyproject.toml
- Update package author to enable package upload
- Add tests to verify package can be installed after it is built
- Update readme badges to be organized by color
> Update package author and add install tests

- .github/workflows/package-build.yml
- .github/workflows/package-testpypi.yml
- README.rst
A separate workflow for uploading to test.pypi.org was needed to simplify the process.
> Implement separate TestPyPI upload workflow

- .github/workflows/package-testpypi.yml
Fixes the TestPyPI upload workflow.
> Fix TestPyPI upload

- .github/workflows/package-testpypi.yml
- CONTRIBUTING.md
- pyproject.toml
- scripts/contributor_setup.py
- scripts/create_post_version_for_testpypi.py
- scripts/modify_project_version.py
- scripts/project_version.py
- scripts/pypi_latest_version.py
The test.pypi.org uploader workflow needed a custom version to function properly. This PR adds that custom post-release version.
> Custom testpypi version creation script

- .github/workflows/package-testpypi.yml
- src/tm_devices/drivers/pi/scopes/tekscope/tekscope.py
- tests/test_device_manager.py
The workflow that uploads to test.pypi.org needed to be refactored and split up to limit elevated permission usage.
> Update test.pypi.org upload workflow

- CHANGELOG.md
- README.rst
- docs/basic_usage.md
- pyproject.toml
- src/tm_devices/__init__.py
- src/tm_devices/device_manager.py
A command-line script was added to make it easier for users to find the available VISA resources.
> Added a command-line script to print the available VISA resources.

- .github/workflows/package-release.yml
- README.rst
Update the main link to ReadtheDocs and add a badge for the package publish workflow.
> Update links in Readme

- .github/workflows/package-release.yml
> Update packaging workflow

- .github/workflows/package-build.yml
- .github/workflows/package-release.yml
- .github/workflows/tek-repo-lint.yml
- .github/workflows/test-code.yml
- .github/workflows/test-docs.yml
- CHANGELOG.md
- pyproject.toml
> ci: Update permissions to allow the workflow to modify GitHub Releases.

- .github/workflows/package-release.yml
- CHANGELOG.md
- README.rst
Update badge displaying total number of downloads in the readme. Also updated the release workflow to run in strict mode to properly indicate failures to upload artifacts to releases.
> Update badge displaying total number of downloads

- CHANGELOG.md
- docs/configuration.md
- pyproject.toml
- scripts/pypi_latest_version.py
- src/tm_devices/device_manager.py
- src/tm_devices/helpers/constants_and_dataclasses.py
- src/tm_devices/helpers/functions.py
- tests/conftest.py
- tests/test_helpers.py
fix: Replaced a third-party package used to check for updates with a few lines of code to perform a request and parse the returned json. This prevents a PermissionsError from happening on some systems. Also added a flag to enable the check for updates, it now defaults to off.
This fixes a potential `PermissionsError` by replacing a third-party package with a direct usage of `requests.get()`. A config option was added, defaulting to `False`, that can enable a check for updates when the `DeviceManager` is first instantiated if the user wants to have that behavior.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to …
> Update the code that checks for package updates

- .github/workflows/package-release.yml
- CHANGELOG.md
- docs/conf.py
- python_semantic_release_templates/.macros.j2
- python_semantic_release_templates/.release_notes.md.j2
- python_semantic_release_templates/CHANGELOG.md.j2
- scripts/check_unreleased_changelog_items.py
> Add template for GitHub Releases

- .github/workflows/deploy-documentation.yml
- README.rst
- pyproject.toml
Created a workflow that can upload and deploy the documentation of tm_devices to GitHub Pages.
Fixes #73 
> docs: Added new workflow which can deploy the documentation to GitHub Pages

- .github/workflows/deploy-documentation.yml
- CONTRIBUTING.md
Updated the contribution guide with a link to GitHub's instructions on commit signing.
> docs: Added instructions on how to set up commit signing with a note explaining that it is required.

- CHANGELOG.md
- src/tm_devices/helpers/functions.py
- tests/test_helpers.py
Update a helper function to handle non-standard software version strings.
> fix: Handle non-standard software versions with alpha characters in the last part of the version

- .pre-commit-config.yaml
- CHANGELOG.md
- src/tm_devices/helpers/constants_and_dataclasses.py
Add USBTMC support for the 3706A device.
> feat: Add USBTMC support for the 3706A device.

- .github/workflows/package-release.yml
- .github/workflows/package-testpypi.yml
ci: Increase timeout when installing tm_devices from pypi servers to avoid issues caused by long wheel build times for packages that tm_devices depends on (such as zeroconf).
> Increase timeout value when installing tm_devices from pypi servers

- CHANGELOG.md
- pyproject.toml
Updated development status to production/stable and removed the Python 3.12 classifier since poetry automatically adds it.
> build: Update package classifiers.

- CHANGELOG.md
- src/tm_devices/drivers/api/rest_api/rest_api_device.py
Added the ability to send raw data to REST API devices.
> feat(rest_api_device): Enable sending raw data for restful api devices.

- .github/workflows/assign-reviewers.yml
Updated the add reviewer workflow to add the admin team to all Pull Requests.
> ci: Add admin team to all Pull Requests.

- CHANGELOG.md
- src/tm_devices/drivers/device.py
- tests/test_afgs.py
When a device is rebooted some properties may change. In order to prevent this from causing issues, a mechanism was added to the `reboot()` method that will reset all cached properties when `.reboot()` is called.
> feat: Added a mechanism to reset cached properties whenever a device is rebooted.

- .pre-commit-config.yaml
- CHANGELOG.md
- CONTRIBUTING.md
- docs/troubleshooting/contributions.md
- pyproject.toml
- scripts/pypi_latest_version.py
- scripts/update_development_dependencies.py
Pinned the linters used (ruff, pyright, pylint) to specific versions to remove failures that can occur when a new version is released that introduces a new linting rule or breaks an existing one. Also added a script that can be used to easily update all pinned dependencies in the pyproject.toml and .pre-commit-config.yaml files.
> Pin the linters used (ruff, pyright, pylint) to specific versions

- CHANGELOG.md
- src/tm_devices/device_manager.py
- src/tm_devices/helpers/constants_and_dataclasses.py
- src/tm_devices/helpers/enums.py
- src/tm_devices/helpers/functions.py
- tests/test_alternative_connection_addresses.py
- tests/test_helpers.py
Update the resource expression detection function to properly handle SOCKET VISA resource expression strings. Also update the `DeviceManager` to be able to handle them.
> fix: Update the function that detects a VISA resource expression to work properly for SOCKET resource expressions.

- .github/workflows/sbom-scan.yml
This PR adds a workflow that will generate a SBOM and perform a scan of that SBOM.
> Add SBOM generation and scanning workflow

- src/tm_devices/device_manager.py
- tests/test_device_manager.py
On first connection the check for `visa_resource.read_stb()` to detect messages left in the output buffer and `visa_resource.clear()` calls will print a warning instead of instantly failing if the visa driver or the device don't fully support those calls. 
> Handle Visa IO Error on first connection

- CHANGELOG.md
- README.rst
> Update supported devices and VISA backends in the readme

- .readthedocs.yml
- src/tm_devices/components/dm_config_parser.py
ReadtheDocs builds are failing because Nodejs is not installed.
> Fix ReadtheDocs builds by installing nodejs

- .github/workflows/package-release.yml
The most recent release of `python-semantic-release` no longer properly signs commits, presumably due to https://github.com/python-semantic-release/python-semantic-release/issues/918. This PR reverts back to the previous versino of `python-semantic-release`.
> ci: Revert python-semantic-release version bump since the GitHub Action no longer properly signs commits

- docs/_static/css/api_labels.css
> docs: Add styling for a new method label

- CHANGELOG.md
- docs/_static/js/copybutton.js
Removed the copy code button from the signatures in the API documentation, since there is never a need to copy that code, it is just for readability and nicely formatted links.
> docs: Update copy code button to not show up on doc signatures in the API documentation

- docs/_templates/mkdocstrings/python/readthedocs/children.html.jinja
> docs: Update wording of API package Modules section

- .github/workflows/package-build.yml
- .github/workflows/sbom-scan.yml
- CHANGELOG.md
- README.md
The binary files and SBOM generated are now all signed with GitHub Attestations.
https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
> Sign all published files

- .github/workflows/check-api-for-breaking-changes.yml
- .github/workflows/publish-api-comparison.yml
This adds workflows that will check if any public APIs have been broken in a Pull Request.
> Add workflows to check for changes that break public APIs

- docs/_static/js/copybutton.js
- docs/_static/js/insert-hr.js
- examples/source_measure_units/2400/smu_2450_linear_sweep_current.py
- examples/source_measure_units/2600/smu_2600_bjt_slow.py
- scripts/contributor_setup.py
- src/tm_devices/device_manager.py
- src/tm_devices/drivers/pi/pi_device.py
- src/tm_devices/helpers/functions.py
- tests/test_afgs.py
- tests/test_devices_legacy_tsp_ieee_cmds.py
- tests/test_smu.py
- tests/test_ss.py
This just has miscellaneous changes that reduce technical debt and fix issues spotted by local SonarLint scans.
> refactor: Miscellaneous refactors to reduce technical debt in variable declarations and comparison operations

- .github/workflows/test-code.yml
- .pre-commit-config.yaml
- pyproject.toml
This adds back the file sorter pre-commit hook for the known words lookup file.
> ci: Add back file sorter hook to pre-commit

- docs/advanced/signal_generators.md
There were some bugs in the signal generation advanced documentation. This PR fixes the bugs that were found.
> docs: Updated the signal generation docs to fix some issues that were found

- .pre-commit-config.yaml
- docs/_templates/mkdocstrings/python/readthedocs/children.html.jinja
- pyproject.toml
The Jinja templates are using deprecated `griffe` code, this updates the templates to use the recommended attributes.
> Update jinja templates

- CHANGELOG.md
- examples/miscellaneous/custom_device_driver_support.py
- pyproject.toml
- src/tm_devices/device_manager.py
- src/tm_devices/drivers/api/rest_api/margin_testers/tmt4.py
- src/tm_devices/drivers/device.py
- src/tm_devices/drivers/pi/data_acquisition_systems/data_acquisition_system.py
- src/tm_devices/drivers/pi/digital_multimeters/digital_multimeter.py
- src/tm_devices/drivers/pi/power_supplies/psu2200/psu2200.py
- src/tm_devices/drivers/pi/scopes/tekscope_2k/tekscope_2k.py
- src/tm_devices/drivers/pi/scopes/tekscope_5k_7k_70k/tekscope_5k_7k_70k.py
- src/tm_devices/drivers/pi/scopes/tso/tsovu.py
- src/tm_devices/drivers/pi/signal_generators/afgs/afg3k.py
- src/tm_devices/drivers/pi/signal_generators/awgs/awg.py
- src/tm_devices/drivers/pi/source_measure_units/smu24xx/smu24xx_interactive.py
- src/tm_devices/drivers/pi/source_measure_units/smu24xx/smu24xx_standard.py
- src/tm_devices/drivers/pi/source_measure_units/smu26xx/smu26xx.py
- src/tm_devices/drivers/pi/source_measure_units/smu60xx/smu6xxx.py
- src/tm_devices/drivers/pi/systems_switches/ss3706a.py
- src/tm_devices/helpers/constants_and_dataclasses.py
- src/tm_devices/helpers/enums.py
- tests/samples/unsupported_device_type_config.yaml
- tests/sim_devices/devices.yaml
- tests/test_device_manager.py
- tests/test_rest_api_device.py
- tests/test_scopes.py
- tests/test_tm_devices.py
- tests/test_unsupported_device_type.py
Unsupported device types can now be added via the DeviceManager (or config file or environment variable). This does raise a warning indicating that functionality is limited.
> Enable adding unsupported device types via the DeviceManager

- .github/workflows/test-code.yml
- .github/workflows/test-docs.yml
- .readthedocs.yml
- pyproject.toml
This converts test-docs.yml into a reusable workflow.
> Convert test-docs.yml to a reusable workflow

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
This updates the contribution guide to provide instructions on how users can track the release status of features/bugfixes.
> docs: Update the contribution guide to provide details on how to track the status of changes in the GitHub repo using issues

- pyproject.toml
- scripts/contributor_setup.py
> build: Update license identifier

- src/tm_devices/device_manager.py
- src/tm_devices/helpers/constants_and_dataclasses.py
- tests/samples/simulated_config.yaml
- tests/test_device_manager.py
- tests/test_generate_waveform.py
fix: Ensure that the default VISA timeout value is not overwritten if a new config is loaded that doesn't specify a default VISA timeout.
Previously, the implicit default of 5000ms would overwrite any custom timeout values, now leaving the config option unset will leave the current setting alone.
> fix: Ensure that the default VISA timeout value is not overwritten if a new config is loaded that doesn't specify a default VISA timeout

- .github/workflows/package-build.yml
- .github/workflows/package-release.yml
- .github/workflows/test-code.yml
- .pre-commit-config.yaml
- docs/configuration.md
ci: Remove pre-commit hook that no longer works on Python 3.8 and replace with one that does
> ci: Remove pre-commit hook that no longer works on Python 3.8 and replace with one that does

- CHANGELOG.md
- docs/basic_usage.md
- examples/scopes/tekscope/save_screenshot.py
- src/tm_devices/driver_mixins/abstract_device_functionality/__init__.py
- src/tm_devices/driver_mixins/abstract_device_functionality/screen_capture_mixin.py
- src/tm_devices/driver_mixins/device_control/pi_control.py
- src/tm_devices/drivers/scopes/tekscope/tekscope.py
- tests/sim_devices/scope/tekscopepc.yaml
- tests/test_scopes.py
feat: Added a screen capture mixin and implemented the functionality for the TekScope family of device drivers
> Add screen capture functionality for TekScope device driver family

- .readthedocs.yml
chore: Remove unused env var from .readthedocs.yml
> chore: Remove unused env var from .readthedocs.yml

- CHANGELOG.md
- src/tm_devices/driver_mixins/device_control/tsp_control.py
Made it so the get_buffers() function does not error out if the buffers are empty.
> fix: allow empty returns from tsp_device.get_buffers()

- CHANGELOG.md
- src/tm_devices/driver_mixins/device_control/tsp_control.py
- tests/sim_devices/smu/smu2601b.yaml
- tests/test_smu.py
updated get_buffers() with logic to handle empty buffer.
> fix: updated get_buffers() with logic to handle empty buffer

- CHANGELOG.md
- src/tm_devices/helpers/functions.py
- tests/test_helpers.py
feat: Added support for a new custom version string format, `"1.2.3-custom.1234+abcdefghi"`
> feat: Added support for a new custom version string format, `"1.2.3-custom.1234+abcdefghi"`

- CHANGELOG.md
- src/tm_devices/helpers/logging.py
The timestamp was improperly formatted with zero padded milliseconds, this change refactors it back to the original 6 digits of precision with microseconds.
> Fixed microsecond representation in log formatting

- .github/workflows/test-code.yml
Many false failures have been observed on MacOS when running pyright as a part of pre-commit. This enables retries to attempt to work around the false failures.
> ci: Allow retries for CI testing on MacOS

- CHANGELOG.md
- src/tm_devices/drivers/awgs/awg70ka.py
Updated the expected error message for the set_output_signal_path method in the AWG70K driver.
Addresses #397
> Update AWG70K driver to properly handle when the DCA output signal path is not supported

- CHANGELOG.md
- src/tm_devices/helpers/logging.py
fix: Updated the logging configuration function to properly display the correct timestamp precision when using colored console logging
> fix: Updated the logging configuration function to properly display the correct timestamp precision when using colored console logging

- CHANGELOG.md
- pyproject.toml
chore: Relax psutil version requirement
> chore: Relax psutil version requirement to >=6.0.0

- CHANGELOG.md
- src/tm_devices/drivers/scopes/tekscope_5k_7k_70k/tekscope_5k_7k_70k.py
- tests/test_scopes.py
Previously a flawed method of determining the total number of physical channel connections on the 70kSX scope series was used. This PR enhances the logic determine the total channel count to allow users to access all 3 channels on SX scopes which have the ATI feature (and therefore have 3 physical channel connections).
Addresses #407
> fix: Fixed the method of determining the total number of physical channel connectors on the 70kSX scope series

- CHANGELOG.md
- src/tm_devices/drivers/scopes/tekscope/tekscope.py
For the internal AFG of the TekScope, set offset after impedance so that it is properly adjusted.
Addresses #409
> Set offset after impedance so that it is properly adjusted 

- CHANGELOG.md
- src/tm_devices/driver_mixins/device_control/pi_control.py
- tests/test_scopes.py
fix: Ensure VISA timeout is reset after reboot in pi_control and update related tests
Addresses #420
> fix: Ensure VISA timeout is reset after reboot in pi_control

- .github/workflows/update-python-and-pre-commit-dependencies.yml
- pyproject.toml
ci: update Python version requirement and pre-commit hook skip list in a github workflow
> ci: update Python version requirement and pre-commit hook skip list in a github workflow

- CHANGELOG.md
- src/tm_devices/drivers/device.py
Updated the `Device.ip_address` property to remove the USB connection type exclusion.
> fix: Attempt to grab the ip_address for all connection types
