.github/CODEOWNERS
.github/auto_assign.yml
.github/workflows/codeql-analysis.yml
.github/workflows/package-build.yml
.github/workflows/test-code.yml
.pre-commit-config.yaml
README.md
src/tm_devices/__init__.py
src/tm_devices/device_manager.py
src/tm_devices/drivers/api/rest_api/rest_api_device.py
tests/test_docs.py

Update workflows and other files based on the public status of the repo.

build: Enable things needed for public package.

---

.github/PULL_REQUEST_TEMPLATE.md
pyproject.toml

This PR adds a template that will pre-populate when contributors open a PR to help them know what is expected.

Add a Pull Request template

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/package-build.yml
.github/workflows/test-code.yml
README.rst
pyproject.toml

Updated the test.pypi.org uploaded version to have a unique version metadata string to prevent duplicate uploads.
This is a temporary hotfix and the entire package build/upload workflow will be updated in the future.

Upload unique dev packages to test.pypi.org

---

.github/workflows/package-testpypi.yml
CONTRIBUTING.md
pyproject.toml

Update the config for python-semantic-release to prevent the tool from accidentally creating a new version without a forced version.

Update python-semantic-release config settings.

---

.github/workflows/package-testpypi.yml

Add a wait time to allow for the newly created version to be installed from test.pypi.org

Add a wait time to allow for the package to be available to install.

---

.gitignore
.readthedocs.yml
docs/conf.py
src/tm_devices/commands/_helpers/generic_commands.py

In order to reduce the documentation build time, the inheritance diagram was removed from the auto-generated API docs.

Reduce doc build time

---

.github/workflows/package-release.yml
.pre-commit-config.yaml
CHANGELOG.md
CONTRIBUTING.md
docs/troubleshooting/contributions.md
pyproject.toml
python_semantic_release_templates/CHANGELOG.md.j2
scripts/check_unreleased_changelog_items.py

ci: Added a workflow and necessary support scripts/templates to enable automated released via GitHub's workflow_dispatch trigger.
Added a workflow that will enable releasing the project to PyPI and GitHub.

Add workflow for official GitHub and PyPI release

---

.github/workflows/package-release.yml

This fixes an issue where an ignored file should not be added to git tracking.

Update git config during package release.

---

.github/workflows/package-release.yml

ci: Add necessary secret usage for workflow to have required permissions to publish updates.
The package release workflow needs some updates to have access to the necessary secrets to be able to make changes to the repo.

Update package release workflow with necessary permissions

---

.github/workflows/package-release.yml

ci: Update semantic release step to not use the docker container.

---

.github/workflows/package-release.yml

ci: Add missing command to workflow.

---

.github/workflows/package-release.yml
.github/workflows/package-testpypi.yml
python_semantic_release_templates/CHANGELOG.md.j2

Updates the release workflow to properly sign the new commits and use secrets/vars to access the necessary account info to make future changes easier. Also updated the changelog template to not include PRs if there are none, though that should never happen.

ci: Update workflow to enable signed commits.

---

.github/workflows/codeql-analysis.yml
.github/workflows/package-release.yml
.github/workflows/tek-repo-lint.yml
.github/workflows/test-code.yml
.github/workflows/test-docs.yml
.pre-commit-config.yaml
CHANGELOG.md
python_semantic_release_templates/CHANGELOG.md.j2

Fix the package release workflow to build the correct version.

Update package release workflow to build correct version

---

.github/workflows/package-release.yml
CHANGELOG.md
README.rst
python_semantic_release_templates/CHANGELOG.md.j2

Update the release workflow to add artifacts to the GitHub Release. Also update the changelog to not cause documentation build failures.

Fix readme links and release workflow

---

.github/workflows/package-release.yml
CHANGELOG.md

fix: Update the version of the semantic release action used to fix a bug with the output version.

---

.github/workflows/package-release.yml
pyproject.toml
src/tm_devices/device_manager.py

ci: Update workflow name and add Python 3.12 classifier

---

src/tm_devices/drivers/pi/scopes/tekscope/tekscope.py

Remove outdated comment

---

docs/basic_usage.md
src/tm_devices/driver_mixins/class_extension_mixin.py

Update the wording in the basic usage document to better indicate how to configure devices.

docs: Update basic usage with better wording for examples.

---

.github/dependabot.yml
examples/scopes/tekscope/get_acquisition_data.py
examples/scopes/tekscope_70k/dpojet/adding_dpojet_measurements.py

fix: Update a few comments to have better wording.

---

.github/workflows/dependency-review.yml

Add a workflow to scan dependencies for security issues.

ci: Added a workflow to scan for security issues in dependencies on all PRs.

---

python_semantic_release_templates/.macros.j2

Update how `python-semantic-release` grabs the pull request numbers.

ci: Update how the changelog generation macro selects PR numbers.

---

CHANGELOG.md
README.rst
src/tm_devices/drivers/api/rest_api/rest_api_device.py
src/tm_devices/drivers/pi/scopes/tekscope/tekscope.py
src/tm_devices/helpers/constants_and_dataclasses.py
tests/test_margin_testers.py
tests/test_scopes.py

Added options for REST API devices to bypass SSL verification and/or allow URL redirects. Also updated the maintainers section of the readme.

Add new options for REST API devices

---

README.rst

Remove the TestPyPI badge from the readme.

docs: Remove the TestPyPI badge from the readme.

---

.pre-commit-config.yaml
CHANGELOG.md
src/tm_devices/commands/_helpers/generic_commands.py
src/tm_devices/components/dm_config_parser.py
src/tm_devices/drivers/pi/pi_device.py
src/tm_devices/drivers/pi/scopes/tekscope/tekscope.py
src/tm_devices/helpers/functions.py
tests/test_helpers.py

A check was added when getting system VISA info that will disable querying backend information when run on macOS with System Integrity Protection enabled.
Relates to #108 

Fix import error on mac with system integrity protection

---

.github/workflows/package-release.yml
.github/workflows/package-testpypi.yml
.pre-commit-config.yaml
SECURITY.md
examples/miscellaneous/adding_devices.py

The release workflow was updated to add a summary showing the release level for easier review during the release process. The docs were also updated with a better example showing how to use a dataclass to update the config options.

Update config docs and release workflow

---

tests/test_afgs.py
tests/test_smu.py

Update tests to try to reduce false failures when running unit tests on macOS.

test: Update tests to try to eliminate false failures when running tests on macOS.

---

.pre-commit-config.yaml
src/tm_devices/device_manager.py

Update ruff version for pre-commit and also update noqa comments.

build: Update version of ruff for pre-commit

---

.github/workflows/test-docs.yml
.pre-commit-config.yaml

Switch the doc building and testing workflow to run on GitHub's publicly available runners based on the updates detailed in https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/

Update doc workflow runners

---

.pre-commit-config.yaml
pyproject.toml

Update linters and pre-commit hooks.

ci: Update pre-commit hooks and linter versions.

---

.pre-commit-config.yaml
CHANGELOG.md
src/tm_devices/drivers/pi/pi_device.py
tests/test_pi_device.py

Fixed PI device close method to catch VisaIOErrors and throw a warning closing a PI device connection.

Update PI Device close method to catch VisaIOErrors

---

CHANGELOG.md
docs/contributing/add_new_driver.md
src/tm_devices/helpers/enums.py
src/tm_devices/helpers/functions.py
tests/test_helpers.py

The `get_model_series()` function was overly complicated. This changes it to use a regex lookup to make it easier to understand.

refactor: Updated the `get_model_series()` function to make it simpler for future maintenance and additions.

---

.github/workflows/update-python-and-pre-commit-dependencies.yml
.pre-commit-config.yaml
scripts/update_development_dependencies.py

When dependabot updates python versions, the pre-commit hook versions need to be updated as well. This PR adds a workflow that will automatically update the pre-commit hooks as a part of the dependabot pull request.

ci: Created a workflow to update python linting dependencies and pre-commit hook versions inside of a PR.

---

.gitignore
pyproject.toml

Update tox to test building the package in a unique environment to prevent race conditions when running tox environments in parallel.

test: Update tox to test building the package in a unique environment to prevent race conditions when running tox environments in parallel.

---

CHANGELOG.md
src/tm_devices/helpers/functions.py

Update the get_model_series() method to only warn the user if the model isn't contained in the list of supported models.

refactor: Update the get_model_series() method to only warn the user if the model isn't contained in the list of supported models.

---

.github/workflows/sbom-scan.yml

Add a step to upload the sarif file as a workflow artifact.

ci: Add a step to upload the sarif file as a workflow artifact.

---

.github/workflows/test-docs.yml
.readthedocs.yml

ci: Update documentation builds to use node.js version 20.

ci: Update documentation builds to use node.js version 20

---

.github/workflows/assign-reviewers.yml
.github/workflows/update-python-and-pre-commit-dependencies.yml

Miscellaneous workflow updates.

Misc. workflow updates

---

CHANGELOG.md
src/tm_devices/commands/_1mlt9u_mdomsodpo/measurement.py
src/tm_devices/commands/_dpo4k_commands.py
src/tm_devices/commands/_dpo4kb_commands.py
src/tm_devices/commands/_mdo3k_commands.py
src/tm_devices/commands/_mdo4k_commands.py
src/tm_devices/commands/_mdo4kb_commands.py
src/tm_devices/commands/_mdo4kc_commands.py
src/tm_devices/commands/_mso4k_commands.py
src/tm_devices/commands/_mso4kb_commands.py

Updated the measurement source selection command for the MDO3K

---

.pre-commit-config.yaml
pyproject.toml
scripts/update_development_dependencies.py

The `docformatter` dependency used to cause issues, those are no longer present, so the version is being bumped.

ci: Update docformatter version, it no longer causes issues.

---

CHANGELOG.md
examples/scopes/tekscope/get_acquisition_data.py

Updated the get_acquisition_data example to select source for the measurement.

---

CHANGELOG.md
python_semantic_release_templates/CHANGELOG.md.j2

The template used to update the changelog had markdown syntax that was causing mdformat to fail during pre-commit checks.

fix: Update Changelog template to prevent pre-commit failures. when creating new versions with python-semantic-version

---

docs/macros.py
mkdocs.yml

This add analytics to the documentation.

docs: Add analytics code for documentation

---

docs/key_features.md

Update the trademark symbols to look better.

docs: Update the trademark symbols

---

.github/workflows/package-build.yml
.github/workflows/package-release.yml
.github/workflows/test-code.yml

This adds testing for installation against all python versions and operating systems that this package supports.

ci: Update build and release workflows to verify the package can be installed for all supported Python versions and Operating Systems

---

.github/workflows/publish-api-comparison.yml
.github/workflows/publish-test-results.yml
.github/workflows/update-python-and-pre-commit-dependencies.yml

The poetry-audit hook can't be run since the dependencies aren't installed for the package. It also doesn't need to be run during the updater process.

ci: Update the updater workflow to skip running poetry-audit during the updater process

---

.github/workflows/package-release.yml
CHANGELOG.md
pyproject.toml

This fixes broken GitHub actions.

Downgrade python-semantic-release to allow release workflow to run

---

.pre-commit-config.yaml
pyproject.toml
scripts/requirements.txt
scripts/update_development_dependencies.py

Previously the pre-commit hooks were using tags to indicate the version of the hook being used. This PR updates the hooks to be pinned using hashes.

Update the script that updates the pre-commit dependencies to update them with frozen hashes

---

pyproject.toml

This just makes a minor tweak to the development dependencies of the package

chore: Remove an unneeded development dependency

---

.github/workflows/check-api-for-breaking-changes.yml
.github/workflows/codeql-analysis.yml
.github/workflows/enforce-community-standards.yml
.github/workflows/package-build.yml
.github/workflows/package-release.yml
.github/workflows/package-testpypi.yml
.github/workflows/publish-api-comparison.yml
.github/workflows/publish-test-results.yml
.github/workflows/sbom-scan.yml
.github/workflows/test-code.yml
.github/workflows/test-docs.yml
.github/workflows/update-python-and-pre-commit-dependencies.yml

chore: Bump the version of tektronix/python-package-ci-cd to v1.3.0 in workflows

chore: Bump the version of tektronix/python-package-ci-cd to v1.3.0 in workflows

---

.github/workflows/update-python-and-pre-commit-dependencies.yml

ci: Skip updating the mdformat repo during the dependency updater workflow

ci: Skip updating the mdformat repo during the dependency updater workflow

---

CHANGELOG.md

CHANGELOG.md line fix

---

docs/_static/css/theme_overrides.css
docs/_templates/mkdocstrings/python/readthedocs/class.html.jinja

fix: Fix the documentation to not show the mermaid tooltip clipping at the top of each page with an inheritance diagram

fix: Fix the documentation to not show the mermaid tooltip clipping at the top of each page with an inheritance diagram

---

src/tm_devices/driver_mixins/device_control/pi_control.py
src/tm_devices/drivers/power_supplies/psu22xx/psu2230.py
src/tm_devices/helpers/functions.py
tests/test_helpers.py

refactor: Separate out the custom handling of different devices' software/firmware version parsing

refactor: Separate out the custom handling of different devices' software/firmware version parsing

---

CHANGELOG.md
pyproject.toml
src/tm_devices/device_manager.py
src/tm_devices/driver_mixins/device_control/pi_control.py
src/tm_devices/helpers/functions.py

feat: Enable turning down the verbosity of failure messages during reboot of a VISA device.

feat: Enable turning down the verbosity of failure messages during reboot of a VISA device

---

docs/.linkchecker.ini
pyproject.toml

test: Ignore pull request URLs when checking links

test: Ignore pull request URLs when checking links

---

CHANGELOG.md
src/tm_devices/device_manager.py
src/tm_devices/driver_mixins/device_control/_abstract_device_control.py
src/tm_devices/driver_mixins/device_control/_abstract_device_visa_write_query_control.py
src/tm_devices/driver_mixins/device_control/pi_control.py
src/tm_devices/driver_mixins/device_control/rest_api_control.py
src/tm_devices/driver_mixins/device_control/tsp_control.py
src/tm_devices/drivers/device.py
src/tm_devices/drivers/scopes/tekscope/tekscope.py
src/tm_devices/drivers/scopes/tekscope/tekscopepc.py
tests/test_smu.py

feat: Converted the previously private `_name_and_alias` property on the `Device` class into a public, cached property called `name_and_alias`

feat: Converted the previously private `_name_and_alias` property on the `Device` class into a public, cached property called `name_and_alias`

---

.gitignore
pyproject.toml

This reduces the number of folders in the root dir that are generated when running all tox envs.

test: Move all distributions built during tox into a subdirectory

---

CHANGELOG.md
src/tm_devices/commands/gen_60xy3r_smu/smu.py
src/tm_devices/commands/gen_6srh1x_smu/smu.py
src/tm_devices/commands/gen_6vynmi_smu/smu.py
src/tm_devices/commands/gen_6xiuc2_smu/smu.py
src/tm_devices/commands/gen_canxny_daq/dmm.py
src/tm_devices/commands/gen_d6b496_dmm/dmm.py
src/tm_devices/commands/gen_d83qe0_dmm/dmm.py
src/tm_devices/commands/gen_e3pief_ss/dmm.py
src/tm_devices/commands/ss3706a_commands.py
tests/auto_gen_cmds_list.json

fix: Fixed the `limit[Y]` commands on certain models which were being generated incorrectly

fix: Fixed the `limit[Y]` commands on certain models which were being generated incorrectly

---

CHANGELOG.md
docs/configuration.md
examples/miscellaneous/disable_command_verification.py
src/tm_devices/device_manager.py
src/tm_devices/drivers/device.py
src/tm_devices/drivers/scopes/tekscope/tekscope.py
src/tm_devices/helpers/constants_and_dataclasses.py
tests/test_config_parser.py
tests/test_extension_mixin.py
tests/test_scopes.py

feat: Add disable_command_verification config file and environment variable option to enable speeding up automation scripts
Addresses #424 

feat: Add disable_command_verification config file and environment variable option to enable speeding up automation scripts

---

scripts/generate_schema.py

ci: Change the schema download link to work around issues with the schemastore domain

ci: Change the schema download link to work around issues with the schemastore domain

---

.pre-commit-config.yaml
pyproject.toml

test: Make sure coverage always uses the `src/` path

test: Make sure coverage always uses the `src/` path

---

pyproject.toml

fix: add Python 3.9 classifier to pyproject.toml for compatibility

fix: add Python 3.9 classifier to pyproject.toml for compatibility

---

.github/workflows/test-docs.yml
.readthedocs.yml
mkdocs.yml

chore: update Node.js and Ubuntu versions in CI configuration for consistency

chore: update Node.js and Ubuntu versions in CI configuration for consistency
